### ISSUE TITLE
Some confusion

### ISSUE THREAD

**Issue by wang-yongpan** [AlongWY/sccdec#1]
Hi,

Q1: Why are the experimental results of the v2 and v1 versions of the paper different? Is there any change?

Q2: how long are you cost for fine-tuning? on 10000 samples?

Thanks!

**Comment by AlongWY** [comment]
A1: In the first version, when calculating the metrics, any correct result from either the first or second decompilation was counted as correct, and only one sample result was counted, which may have introduced some randomness and resulted in higher scores. In the second version, we took the last checkpoint and fixed this error, and the metrics were calculated using the average of 5 samples to reduce random error.
A2: About 9 hours for 3 epochs.

**Comment by wang-yongpan** [comment]
ok, i got it. thanks for your reply~

**Comment by AlongWY** [comment]
The lora model and dataset has been made public.

**Comment by wang-yongpan** [comment]
Great!

In addition, i found that the exebench dataset has three optimization options (O0, O3, Os). If you only use these for fine tuning, but you are evaluating four options (O0-O3), does this have an impact?

**Comment by AlongWY** [comment]
We use the code, but recompile the code to these four options (O0-O3) for training.

**Comment by wang-yongpan** [comment]
how can i obtain the source code of exebench?

**Comment by AlongWY** [comment]
we download the exebench fron [huggingface](https://huggingface.co/datasets/jordiae/exebench)

**Comment by wang-yongpan** [comment]
ok, you mean the 'func_def' keyword is the function source code?

**Comment by AlongWY** [comment]
yes

**Comment by wang-yongpan** [comment]
but i failed to compile them. because they all have undeclared identifiers.
<img width="566" alt="屏幕截图 2024-10-09 171149" src="https://github.com/user-attachments/assets/93e28313-8b9c-4fd2-bbbc-8d8fe506d895">

**Comment by AlongWY** [comment]
have  you follow my [script](https://github.com/AlongWY/sccdec/blob/main/src/sccdec/data.py) ?
The script is my script to process exebench.
The processed dataset is published in [huggingface](https://huggingface.co/datasets/ylfeng/sccdec-dataset).

maybe you need concat `synth_deps` and `func_def` to compile.

**Comment by wang-yongpan** [comment]
ok, i c
